services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: test_task
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: always

  api:
    build:
      context: ./api
#    image: lolman135/simple-shop
    container_name: api
    depends_on:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_task
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DLL_AUTO: update
      LOADING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - '8080:8080'
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    depends_on:
      - postgres
    ports:
      - '6379:6379'
#    volumes:
#      - redis-data/data
    command:
      ["redis-server"]
    restart: always

volumes:
  postgres-data:
#  redis-data: